# Generated by Django 3.1.2 on 2020-10-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.CharField(max_length=30)),
                ('bio', models.TextField(max_length=500)),
                ('Phone', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Landing', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=500)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awward.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design', models.IntegerField()),
                ('Usability', models.IntegerField()),
                ('Content', models.IntegerField()),
                ('Average', models.IntegerField()),
                ('Rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awward.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awward.project')),
            ],
        ),
    ]
