# Generated by Django 3.1.2 on 2020-10-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0003_auto_20201024_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(upload_to='', verbose_name='profiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Landing',
            field=models.ImageField(upload_to='landings/'),
        ),
    ]
