# Generated by Django 3.1.2 on 2020-10-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0004_auto_20201025_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
